dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  only:
  - master
  - dev
  - test

install:
  - pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "hackydojo"
    token:
      secure: "nUBOdEbEwzAT2yDtZEqP0mWt2XRCz5Cees0WANUthKMF/IMcf9HCC7xeZ+FnwxKP1/la+2vtelYfDmP5UxJllYVwvD6f60h/U96nB6ggPUK/J5x0iCMSivnb6qrcRI58rY3luHAaf4LdNX9Yfqhj/jKE0RHHQ/qn5l44nX59qxpWSWoo6trZyzeT9tbjoktR0g/0Di+vzcgLOIDahgxmTIncuWK8bgG9eREKeaeOOQND5nOJj8Ck7U6xl4QXku+ZvNcAfSCTmH2ELidseCsJMMJRtnlaVWk9GJH+uyU3LIjwn2ZCH9D2e/xUjU4cWXbOfEGKT8McjPcUg2zgKQwbtdduo17revoF2/1wLKT5WkKl/RAlOsTqTa0A/W57ohZTDEI6qOBkHSalvbtaNY1rLmzTtdLJUdtflKry6jQhLeQ4+TmOHq2jEegd/5FTtpNeSVOcToZa8OhnyQ71n3kbNGG/ZlsCNBzjPVKmAhrIxja9Wa85CUpyDng0voKnFhpdQ6og5xDZqFPt1SZrgeD1YbGB7/UWoktcVHX2MGYSPLc/NgI82kuTLbQIY6jsq//BIjRsliwwl0rH8Jl5AYVV/aoR2DnxB0h7uR4T3GOApVNlNR0CK/anuaYqpNVwGdgG50Jkluk3du+v7bd0vY7WgDskJLka9SSXEyfPxL0vWmo="

script:
  - sh run_tests.sh
  - sonar-scanner



