dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  only:
  - master
  - dev
  - test

install:
  - pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "hackydojo"
    token:
      secure: "hUdpLLXouhYedBdFzf0Wj72bMD1Yo7fYK1HsUMHKW88WDDNs9dVobZpfL3CmSoasnX5lWvt5lVee2NiJhMqz2hgEFNZ07Ev+OMWJT/Vrx/Mo6XMiE3f2HMdyWyWr4zcYzAt/KAnc3zxY52aHnmGPXEbsbJh6fw9+HfXcg2BAfKKYqDN3OEW4uesDKTvS559tb6rG6vtUOnXfihfwEsIotvV9bBs3IW6GFoi9RYDg42hBjjU6nXOezWyeC+9mCA0DDwEEagLxRZGVz8ImN3/j59Qb6AG5NPHeePexHfLofqPVSISDfHWUB0JlPjJNo3yEwXxWSNOBf/7nd6RLDv5hFK1yMa73TA5sJQ7h9n4x3/rslKxDXS+MfmO1yF5puHrN01abg2cvdK0zCAhlfPUT4NYcftmRDmixbKkFsAXaSWZ8TzfQKHZBMl4KoWGmuyxPMGtWU9+NgcORaBShYfubBGncf7ADzSS72R0eEF0t9l5SEe1xAzF2U3guG3M7QdArXVSoYHplh6oeUWKwdnh5at5VrjmAqReqabj7JepteHhEkp04fofYuVG6F42FLbYTkY0lJKdP+8pOqNnm1mhLZ811VD1huM6C/G+TbXVIbRITybrG2K02jtfEwv/V8FpOrX/OFsawRvL40PspEVDs0XtNonl/LjFJn1vSldx5Xj4="

script:
  - sh run_tests.sh
  - sonar-scanner



